name: Build and Deploy

on:
  push:
    branches: [ '*' ]

env:
  IMAGE_NAME: my-image
  AWS_REGION: us-east-1
  # FARGATE_CLUSTER: <YOUR_AWS_FARGATE_CLUSTER>
  # FARGATE_TASK_DEFINITION: <YOUR_AWS_FARGATE_TASK_DEFINITION>

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ml-basics
          IMAGE_TAG: demo_image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Build and Push Docker image
      #   run: |
      #     docker build --tag ${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ github.sha }} .
      #     docker tag ${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ github.sha }} ${{ env.AWS_ECR_REPOSITORY }}:latest
      #     docker push --all-tags ${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ github.sha }}
         # docker push ${{ env.AWS_ECR_REPOSITORY }}:latest

      # - name: Deploy to AWS Fargate
      #   uses: aws-actions/amazon-ecs-run-task@v1
      #   with:
      #     cluster: ${{ env.FARGATE_CLUSTER }}
      #     task-definition: ${{ env.FARGATE_TASK_DEFINITION }}
      #     launch-type: FARGATE
      #     network-configuration: |
      #       awsvpcConfiguration={
      #         subnets=["subnet-12345678"],
      #         securityGroups=["sg-12345678"],
      #         assignPublicIp="ENABLED"
      #       }
